pub mod arrow;
pub mod avro;
pub mod csv;
pub mod deserializer;
pub mod erlang;
pub mod error;
pub mod excel;
pub mod flatten;
pub mod html;
pub mod io;
pub mod json;
pub mod reader;
pub mod sql;
pub mod util;
pub mod xml;

pub use crate::erlang::ReaderOptions;
pub use crate::erlang::WriterOptions;
pub use crate::error::Error;
pub use crate::error::Result;
pub use crate::reader::DataType;
pub use crate::reader::Field;
pub use crate::reader::Schema;
pub use crate::reader::Value;
pub use crate::reader::ValueReader as Reader;
